# Generated by Django 4.1.7 on 2023-02-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_activity_date_created_lesson_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Questionnaire',
            new_name='Question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='name',
        ),
    ]
