# Generated by Django 4.1.7 on 2023-02-22 15:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_answer_rename_questionnaire_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pages.question'),
            preserve_default=False,
        ),
    ]
