# Generated by Django 4.1.7 on 2023-02-22 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_answer_is_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='description',
        ),
    ]
