# Generated by Django 4.1.7 on 2023-02-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_answer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'EASY MODE'), ('medium', 'MEDIUM MODE'), ('hard', 'HARD MODE')], default='easy', max_length=20),
        ),
    ]
