# Generated by Django 4.1.7 on 2023-02-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_lesson_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='activity',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'EASY MODE'), ('medium', 'MEDIUM MODE'), ('hard', 'HARD MODE')], default='easy', max_length=20),
        ),
    ]
