# Generated by Django 4.1.7 on 2023-02-28 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_remove_lesson_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.level'),
            preserve_default=False,
        ),
    ]
