# Generated by Django 4.1.7 on 2023-02-28 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_useranswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='question',
        ),
    ]
