# Generated by Django 4.1.7 on 2023-03-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_remove_useranswer_question'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='useranswer',
            constraint=models.UniqueConstraint(fields=('user', 'answer'), name='user_answer'),
        ),
    ]
