# Generated by Django 4.1.7 on 2023-03-13 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0017_alter_finishedlesson_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedlesson',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.lesson'),
        ),
        migrations.AlterField(
            model_name='finishedlesson',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='finishedlesson',
            constraint=models.UniqueConstraint(fields=('lesson', 'user'), name='lesson_user'),
        ),
    ]
